// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCv_M7Dg_7UWtdT4yTwQmA3PpOE4Yh2LWo',
    appId: '1:511831403903:web:eae4ab0fbb97f9e97dbe4a',
    messagingSenderId: '511831403903',
    projectId: 'authfire-5bdea',
    authDomain: 'authfire-5bdea.firebaseapp.com',
    storageBucket: 'authfire-5bdea.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpi2FHcAttPaKy3P59SoM_-dnExJHOQj4',
    appId: '1:511831403903:android:2a85d2f6e88e521a7dbe4a',
    messagingSenderId: '511831403903',
    projectId: 'authfire-5bdea',
    storageBucket: 'authfire-5bdea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDusDrnfIGTDix4-q8wzVTPnfYS9mytjvQ',
    appId: '1:511831403903:ios:c09e3169017c777b7dbe4a',
    messagingSenderId: '511831403903',
    projectId: 'authfire-5bdea',
    storageBucket: 'authfire-5bdea.appspot.com',
    iosClientId: '511831403903-2pthfkpr7vc09nutkg0npo7na564k88l.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopfy',
  );
}
